name: PR testing

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  build-lint-test:
    name: Test on ${{ matrix.os }} (node ${{ matrix.node-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: ["22", "24"]
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0 https://github.com/actions/checkout/releases/tag/v6.0.0

      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0 https://github.com/actions/setup-node/releases/tag/v6.0.0
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: npm

      - name: Install dependencies
        shell: bash
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint
        if: matrix.os == 'ubuntu-latest'
        run: npm run lint

      - name: Test
        run: npm run test
